_core:
  default_config_hash: pAf8OfMLO0FLARORHBHqHphfpO56Gn4fqpYVGfYWiSE
contexts:
  -
    context: ''
    translations:
      -
        source: 'Search Species Information'
        translation: 'Search Manatee Information'
      -
        source: Species
        translation: Manatee
      -
        source: species
        translation: manatee
      -
        source: 'Species Births'
        translation: 'Manatee Births'
      -
        source: 'Species ID'
        translation: 'Animal ID'
      -
        source: 'Species Number'
        translation: 'Manatee Number'
      -
        source: 'Tracking ID Information'
        translation: 'Animal ID Information'
      -
        source: 'Tracking Number'
        translation: MLog
      -
        source: 'Tracking ID'
        translation: 'Animal ID'
