name: 'FWS RCGR Content'
description: 'FWS RCGR sample content.'
type: 'Site'
config:
  actions:
    # Set home page
    system.site:
      simple_config_update:
        page.front: /node/7
        page.403: /node/10
        page.404: /node/9
