name: 'FWS Sighting User'
description: 'FWS Sighting user fields, roles and permissions.'
type: 'Site'

install:
  - fws_user

config:
  actions:
    openid_connect.settings:
      simple_config_update:
        always_save_userinfo: true
        connect_existing_users: true
        override_registration_settings: false
        end_session_enabled: false
        user_login_display: above
        redirect_login: user
        redirect_logout: ''
        userinfo_mappings:
          timezone: zoneinfo
          field_first_name: given_name
          field_last_name: family_name
          field_phone: phone_number
    user.role.authenticated:
      simple_config_update:
        permissions:
          - 'access user profiles'
    core.entity_form_display.user.user.default:
      simple_config_update:
        content:
          account:
            weight: -10
            region: content
            settings: {  }
            third_party_settings: {  }
          contact:
            weight: 5
            region: content
            settings: {  }
            third_party_settings: {  }
          field_first_name:
            weight: 7
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
            type: string_textfield
            region: content
          field_last_name:
            weight: 8
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
            type: string_textfield
            region: content
          field_phone:
            weight: 9
            settings:
              placeholder: ''
            third_party_settings: {  }
            type: telephone_default
            region: content
          field_start_date:
            weight: 10
            settings: {  }
            third_party_settings: {  }
            type: datetime_default
            region: content
