id: node.species_id_results.field_region
field_name: field_region
entity_type: node
bundle: species_id_results
label: 'Geographic Region'
description: ''
required: false
translatable: true
default_value: {  }
dependencies:
  config:
    - field.storage.node.field_region
    - node.type.species_id_results
    - taxonomy.vocabulary.geographic_region
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      geographic_region: geographic_region
field_type: entity_reference
