variables:
  COMPOSER_MEMORY_LIMIT: -1
  COMPOSER_AUTH: '{"gitlab-token":{"gitlab.djcase.com":"${CI_JOB_TOKEN}"}}'

stages:
  - test

test:
  stage: test
  image: ubuntu:20.04
  before_script:
    # System updates and basic dependencies
    - apt-get update
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:ondrej/php
    - apt-get install -y ca-certificates curl gnupg

    # Install Node.js 20.12.2 using nvm
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - . "$NVM_DIR/nvm.sh"
    - nvm install 20.12.2
    - nvm use 20.12.2

    # Install PHP and other dependencies
    - apt-get install -y php8.3-cli php8.3-mbstring php8.3-sqlite3 php8.3-xml php8.3-curl php8.3-gd php8.3-zip xvfb unzip git

    # Install Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer config --global gitlab-token.gitlab.djcase.com ${CI_JOB_TOKEN}
  script:
    - composer install
    - composer validate
    - composer normalize --dry-run
    - vendor/bin/drush site:install minimal --verbose -y --db-url=sqlite://tmp/site.sqlite --site-name="U.S. Fish & Wildlife Service" --account-name=admin --account-pass=admin
    - cd tests/cypress
    - npm install
    - cp cypress.config.js.shippable cypress.config.js
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1280x1024x24 &
    - npm run cypress
