variables:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: "sqlite://tmp/site.sqlite"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

stages:
  - build
  - test

ddev-setup:
  stage: build
  image: ghcr.io/ddev/ddev-gitlab-ci:v1.23
  variables:
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1
  services:
    - docker:dind
  script:
    - ddev config global --no-bind-mounts=true
    - ddev config --project-type=drupal10 --php-version=8.2
    - ddev start
    - ddev composer install
    - ddev composer validate

test:php8.2:
  stage: test
  needs: [ddev-setup]
  image: ghcr.io/ddev/ddev-gitlab-ci:v1.23
  variables:
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1
  services:
    - docker:dind
  script:
    - ddev composer normalize --dry-run
    - ddev drush site-install minimal --verbose --yes --db-url=sqlite://tmp/site.sqlite --account-name=admin --account-pass=admin
    - ddev php core/scripts/drupal -v recipe ../recipes/fws-core
    - ddev drush runserver "$SIMPLETEST_BASE_URL" &
    - until curl -s "$SIMPLETEST_BASE_URL"; do true; done > /dev/null
    - ddev phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php
    - cd tests/cypress
    - npm install
    - cp cypress.config.js.shippable cypress.config.js
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1280x1024x24 &
    - npm run cypress
