variables:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: "sqlite://tmp/site.sqlite"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

stages:
  - build
  - test

setup:
  stage: build
  image: ubuntu:20.04
  before_script:
    # Add PHP repository
    - apt-get update
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:ondrej/php
    # Install Node.js repository
    - apt-get install -y ca-certificates curl gnupg
    - mkdir -p /etc/apt/keyrings
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    # Update and install dependencies
    - apt-get update
    - apt-get install -y curl php8.1-cli php8.1-mbstring php8.1-sqlite3 php8.1-xml unzip git nodejs
    # Install Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    # Install npm (comes with Node.js)
  script:
    - composer install
    - composer validate
    - composer normalize --dry-run

test:
  stage: test
  image: ubuntu:20.04
  before_script:
    # Add PHP repository
    - apt-get update
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:ondrej/php
    # Install Node.js repository
    - apt-get install -y ca-certificates curl gnupg
    - mkdir -p /etc/apt/keyrings
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    # Update and install dependencies
    - apt-get update
    - apt-get install -y php8.1-cli php8.1-mbstring php8.1-sqlite3 php8.1-xml xvfb curl nodejs
    # Set up Drupal
    - php ./web/core/scripts/drupal install minimal --verbose --yes --db-url=sqlite://tmp/site.sqlite --account-name=admin --account-pass=admin
    - php ./web/core/scripts/runserver.php "$SIMPLETEST_BASE_URL" &
    - until curl -s "$SIMPLETEST_BASE_URL"; do true; done > /dev/null
  script:
    - ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php
    - cd tests/cypress
    - npm install
    - cp cypress.config.js.shippable cypress.config.js
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1280x1024x24 &
    - npm run cypress
