variables:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: "sqlite://tmp/site.sqlite"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

stages:
  - build
  - test

setup:
  stage: build
  image: ubuntu:20.04
  before_script:
    # Update and install required dependencies
    - apt-get update && apt-get install -y \
        curl \
        php-cli \
        php-mbstring \
        php-sqlite3 \
        php-xml \
        unzip \
        git \
        composer \
        npm
    # Install Drupal dependencies
    - composer install
    - composer validate
  script:
    # Validate the project setup
    - composer normalize --dry-run

test:
  stage: test
  image: ubuntu:20.04
  before_script:
    # Ensure required dependencies are installed
    - apt-get update && apt-get install -y \
        php-cli \
        php-mbstring \
        php-sqlite3 \
        php-xml \
        xvfb \
        curl \
        npm
    # Set up a Drupal site
    - php ./web/core/scripts/drupal install minimal --verbose --yes --db-url=sqlite://tmp/site.sqlite --account-name=admin --account-pass=admin
    - php ./web/core/scripts/runserver.php "$SIMPLETEST_BASE_URL" &
    # Wait for server to be ready
    - until curl -s "$SIMPLETEST_BASE_URL"; do true; done > /dev/null
  script:
    # Run PHPUnit tests
    - ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php
    # Set up Cypress for end-to-end tests
    - cd tests/cypress
    - npm install
    - cp cypress.config.js.shippable cypress.config.js
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1280x1024x24 &
    - npm run cypress
