variables:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: "sqlite://tmp/site.sqlite"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

default:
  image: php:8.2-cli

.php_template: &php_template
  before_script:
    # Update package lists and install dependencies
    - apt-get update && apt-get install -y libpng-dev libsqlite3-dev unzip git curl npm xvfb
    # Install PHP extensions
    - docker-php-ext-install gd sqlite3
    # Install Composer
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - composer --verbose self-update --$COMPOSER_CHANNEL

build:php8.2:
  <<: *php_template
  variables:
    COMPOSER_CHANNEL: "stable"
  script:
    - composer --version
    - composer --verbose validate
    - composer --verbose install
    - composer normalize --dry-run
    - ./vendor/bin/drush site-install minimal --verbose --yes --db-url=sqlite://tmp/site.sqlite --account-name=admin --account-pass=admin
    - php core/scripts/drupal -v recipe ../recipes/fws-core
    - ./vendor/bin/drush runserver "$SIMPLETEST_BASE_URL" &
    - until curl -s "$SIMPLETEST_BASE_URL"; do true; done > /dev/null
    - ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php
    - cd tests/cypress
    - npm install
    - cp cypress.config.js.shippable cypress.config.js
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1280x1024x24 &
    - npm run cypress

test-composer:
  image: php:8.2-cli
  variables:
    COMPOSER_VERSION: "2.2"
  before_script:
    - apt-get update && apt-get install -y libpng-dev libsqlite3-dev unzip git curl
    - docker-php-ext-install gd sqlite3
    - curl -sS https://getcomposer.org/installer | php -- --version=$COMPOSER_VERSION
    - mv composer.phar /usr/local/bin/composer
  script:
    - composer --version
    - |
      if composer --verbose install; then
        exit 1
      else
        exit 0
      fi
