version: 1.3.0

services:
  - php:
      version: 8.3
  - mysql
  - memcached

events:
  build:
    steps:
      - setup-composer:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - echo "Installing composer dependencies"
            - composer install
            - echo "$PWD"
      - test-composer:
          type: script
          script:
            - echo "Running PHPSTAN scans"
            - composer phpstan
      - setup-theme:
          type: script
          script:
            - cd web/themes/custom/fws_raf
            - echo "Installing npm dependencies"
            - npm install
            - npm run build
      
            