version: 1.3.0

services:
  - php:
      version: 8.3
  - mysql
  - memcached

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install
            