fws_subpages.fws_subpage_config.*:
    type: fws_search_app_config
    label: 'Search app config'
    mapping:
      id:
        type: string
        label: 'ID'
      label:
        type: label
        label: 'Label'
      index:
        type: string
        label: 'Index'
      root:
        type: string
        label: 'Root'
      config:
        type: string
        label: 'Config'