#!/bin/bash

## Description: Installs FWS Manatee.

ddev composer install
ddev drush site:install minimal --verbose -y --site-name="FWS: Eastern Population Sandhill Crane Data Entry Portal" --account-name=admin --account-pass=admin
ddev drush recipe ../recipes/fws-core
# ddev drush scr ../scripts/eps/install-cleanup.php
ddev drush cr
ddev drush cr
ddev drush recipe ../recipes/fws-eps-content

# ddev drush webform-libraries-download

ddev drush uli
