#!/bin/bash

## Description: Install the RCGR multisite
## Usage: install-rcgr
## Example: "ddev install-rcgr"

ddev composer install

# Ensure we're using the correct site URI
SITE_URI="rcgr.ddev.site"

# Run the site installation
ddev drush -l $SITE_URI site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: Resident Canada Goose Registration"

# Install recipes
ddev drush -l $SITE_URI recipe ../recipes/fws-core
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI scr ../scripts/rcgr/install-cleanup.php
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-content
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-taxonomy
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-node
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-reports
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-user
ddev drush -l $SITE_URI en fws_goose -y

# Run import scripts

# Import states and flyways vocabularies in the correct order
echo "Importing states vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php states 100 1

echo "Importing flyways vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php flyways 100 1

# Run states again to update with flyway references that now exist
echo "Updating states with flyway references..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php states 100 1

# Import other vocabularies
echo "Importing application_status vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php application_status 100 1

echo "Importing applicant_request_type vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php applicant_request_type 100 1

echo "Importing country vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php country 100 1

echo "Importing registrant_type vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php registrant_type 100 1

echo "Importing restricted_counties vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php restricted_counties 100 1

echo "Importing california_access_key vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php california_access_key 100 1

# echo "Importing permits..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-reports.php 100

# Clear the cache to ensure all entities are properly registered
ddev drush -l $SITE_URI cr

ddev drush -l $SITE_URI uli
