#!/bin/bash

## Description: Install the Aerial multisite
## Usage: install-aerial
## Example: "ddev install-aerial"

ddev composer install

# Ensure we're using the correct site URI
SITE_URI="aerial.ddev.site"

# Run the site installation
ddev drush -l $SITE_URI site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: Aerial Observer Training and Testing Resources"

# Install recipes
ddev drush -l $SITE_URI recipe ../recipes/fws-core
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI scr ../scripts/aerial/install-cleanup.php
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI recipe ../recipes/fws-aerial-taxonomy
ddev drush -l $SITE_URI en -y aerial_videos
ddev drush -l $SITE_URI en -y fws_counting
ddev drush -l $SITE_URI en -y fws_id_test
ddev drush -l $SITE_URI recipe ../recipes/fws-aerial-content
ddev drush -l $SITE_URI recipe ../recipes/fws-aerial-media
ddev drush -l $SITE_URI recipe ../recipes/fws-aerial-tests
ddev drush -l $SITE_URI recipe ../recipes/fws-aerial-user
ddev drush -l $SITE_URI recipe ../recipes/fws-aerial-reports
ddev drush -l $SITE_URI scr ../scripts/aerial/import-users.php
ddev drush -l $SITE_URI scr ../scripts/aerial/import-terms.php
ddev drush -l $SITE_URI scr ../scripts/aerial/import-species-photos.php
ddev drush -l $SITE_URI scr ../scripts/aerial/import-species-videos.php
# Import sample test data.
ddev drush -l $SITE_URI scr ../scripts/aerial/import_test_data.php 100
ddev drush -l $SITE_URI cr

ddev drush -l $SITE_URI uli
