#!/bin/bash

## Description: Install the Aerial multisite
## Usage: install-falconry
## Example: "ddev install-falconry"

ddev composer install

# Ensure we're using the correct site URI
SITE_URI="falcon.ddev.site"

# Run the site installation
ddev drush -l $SITE_URI site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: State/Federal Falconry 3-186A Database"

# Install recipes
ddev drush -l $SITE_URI recipe ../recipes/fws-core
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI scr ../scripts/falcon/install-cleanup.php
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-taxonomy
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-user
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-node
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-content
ddev drush -l $SITE_URI cr

# Run import scripts
ddev drush -l $SITE_URI scr ../scripts/falcon/import-taxonomies.php
ddev drush -l $SITE_URI scr ../scripts/falcon/import-users.php 10
ddev drush -l $SITE_URI scr ../scripts/falcon/import_species_images.php

ddev drush -l $SITE_URI uli
