#!/bin/bash

## Description: Install the Aerial multisite
## Usage: install-aerial
## Example: "ddev install-aerial"

ddev composer install

ddev import-db --database=aerial --file=./scripts/empty.sql

# Ensure we're using the correct site URI
SITE_URI="aerial.ddev.site"

# Run the site installation
ddev drush -l $SITE_URI site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: Aerial Observer Training and Testing Resources" \
  --config-dir=../config/sync/aerial

# Run install cleanup script
ddev drush -l $SITE_URI scr ../scripts/aerial/install-cleanup.php

# Install aerial content recipe
ddev drush -l $SITE_URI recipe ../recipes/fws-aerial-content

# Import data
ddev drush -l $SITE_URI scr ../scripts/aerial/import-users.php
ddev drush -l $SITE_URI scr ../scripts/aerial/import-terms.php
ddev drush -l $SITE_URI scr ../scripts/aerial/import-species-photos.php
ddev drush -l $SITE_URI scr ../scripts/aerial/import-species-videos.php
# Import sample test data.
ddev drush -l $SITE_URI scr ../scripts/aerial/import_test_data.php 100
ddev drush -l $SITE_URI cr

ddev drush -l $SITE_URI uli
