#!/bin/bash

## Description: Installs FWS.

ddev composer install
ddev drush site:install minimal --verbose -y --site-name="FWS: Captive Manatee Database" --account-name=admin --account-pass=admin
ddev drush cr
ddev drush recipe ../recipes/fws-core
# ddev drush webform-libraries-download
ddev drush cr

ddev drush scr ../scripts/install-cleanup.php

ddev drush recipe ../recipes/fws-manatee
ddev drush uli
