#!/bin/bash

## Description: Install the RCGR multisite
## Usage: install-rcgr
## Example: "ddev install-rcgr"

ddev composer install

# Ensure we're using the correct site URI
SITE_URI="rcgr.ddev.site"

# Run the site installation
ddev drush -l $SITE_URI site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: Resident Canada Goose Registration"

# Install recipes
ddev drush -l $SITE_URI recipe ../recipes/fws-core
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI scr ../scripts/rcgr/install-cleanup.php
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-user
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-content
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-taxonomy
ddev drush -l $SITE_URI recipe ../recipes/fws-rcgr-node
ddev drush -l $SITE_URI cr

# Run import scripts
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-users.php 10

# Import states and flyways vocabularies in the correct order
echo "Importing states vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php states 1000 1

echo "Importing flyways vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php flyways 1000 1

# Run states again to update with flyway references that now exist
echo "Updating states with flyway references..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php states 1000 1

# Import other vocabularies
echo "Importing application_status vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php application_status 1000 1

echo "Importing applicant_request_type vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php applicant_request_type 1000 1

echo "Importing country vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php country 1000 1

echo "Importing registrant_type vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php registrant_type 1000 1

echo "Importing restricted_counties vocabulary..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-vocab.php restricted_counties 1000 1

echo "Importing permits..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-permits.php 1000

echo "Importing locations..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-locations.php 1000

echo "Importing names..."
ddev drush -l $SITE_URI scr ../scripts/rcgr/import-names.php 1000

ddev drush -l $SITE_URI uli
