#!/bin/bash

## Description: Installs FWS Manatee.

ddev composer install
ddev drush site:install minimal --verbose -y --site-name="FWS: Manatee Rescue and Rehabilitation Database" --account-name=admin --account-pass=admin --config-dir=../config/sync/manatee
ddev drush scr ../scripts/manatee/install-cleanup.php
ddev drush recipe ../recipes/fws-manatee-content

ddev drush config:set system.site page.front /node/2 -y

ddev drush cr

# Import taxonomy and nodes.
./scripts/manatee/import-taxonomy.sh && ./scripts/manatee/import-nodes.sh

# ddev drush webform-libraries-download

ddev drush uli
