#!/bin/bash

## Description: Installs FWS.

ddev composer install
ddev drush site:install minimal --verbose -y
ddev drush recipe ../recipes/fws-core
# ddev drush webform-libraries-download
ddev drush cr

ddev drush scr ../scripts/install-cleanup.php
ddev drush uli
