#!/bin/bash

## Description: Install the Falconry multisite
## Usage: install-falconry
## Example: "ddev install-falconry"

ddev composer install

ddev import-db --database=falcon --file=./scripts/empty.sql

# Ensure we're using the correct site URI
SITE_URI="falcon.ddev.site"

# Run the site installation
ddev drush -l $SITE_URI site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: State/Federal Falconry 3-186A Database"

# Install recipes
ddev drush -l $SITE_URI recipe ../recipes/fws-core
ddev drush -l $SITE_URI cr
ddev drush -l $SITE_URI scr ../scripts/falcon/install-cleanup.php
ddev drush -l $SITE_URI en -y fws_falcon_user fws_falcon_permit
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-taxonomy
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-node
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-user
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-content
ddev drush -l $SITE_URI recipe ../recipes/fws-falcon-reports
ddev drush -l $SITE_URI cr

# Run import scripts
ddev drush -l $SITE_URI scr ../scripts/falcon/import-taxonomies.php
ddev drush -l $SITE_URI scr ../scripts/falcon/create-users.php
ddev drush -l $SITE_URI scr ../scripts/falcon/import-users.php 10
ddev drush -l $SITE_URI scr ../scripts/falcon/import_species_images.php
ddev drush -l $SITE_URI scr ../scripts/falcon/import_species_3186a.php 1000

ddev drush -l $SITE_URI uli
