#!/bin/bash

## Description: Installs FWS.

ddev composer install
ddev drush site:install minimal --verbose -y --site-name="U.S. Fish & Wildlife Service" --account-name=admin --account-pass=admin
ddev drush cr
ddev drush recipe ../recipes/fws-core
# ddev drush webform-libraries-download
ddev drush cr

ddev drush uli
