status: 1
pattern: '[node:field_permit_no] [node:field_applicant_business_name]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.permit
new_content_behavior: 0
