#!/bin/bash

## Description: Install the EPS multisite
## Usage: install-eps
## Example: "fin install-eps"

fin composer install

# Run the site installation
# Note: Docksal handles the site URI automatically, so -l is omitted compared to DDEV.
fin drush site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: Eastern Population Sandhill Crane Data Entry Portal" \
  --config-dir=../config/sync/eps

# Run install cleanup script
fin drush scr ../scripts/eps/install-cleanup.php

# Install eps content recipe
fin drush recipe ../recipes/fws-eps-content

# Set front page
# fin drush config:set system.site page.front /node/1 -y

# Import data
fin drush scr ../scripts/eps/import-users.php
fin drush scr ../scripts/eps/import-sightings.php

fin drush cr
fin drush uli
