#!/bin/bash

## Description: Install the EPS multisite
## Usage: install-eps
## Example: "fin install-eps"

fin composer install

# Run the site installation
fin drush -l site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --sites-subdir=eps \
  --verbose \
  --site-name="FWS: Eastern Population Sandhill Crane Data Entry Portal"

# Install recipes
fin drush -l recipe ../recipes/fws-core
fin drush -l cr
fin drush -l scr ../scripts/eps/install-cleanup.php
fin drush -l cr
fin drush -l recipe ../recipes/fws-sighting-taxonomy
fin drush -l recipe ../recipes/fws-sighting-node
fin drush -l recipe ../recipes/fws-sighting-reports
fin drush -l recipe ../recipes/fws-sighting-blocks
fin drush -l recipe ../recipes/fws-sighting-user
fin drush -l recipe ../recipes/fws-eps-content
fin drush -l en -y fws_sighting

# Import users
# fin drush -l scr ./scripts/eps/import-users.php

fin drush -l uli
