#!/bin/bash

## Description: Installs FWS Manatee.

fin composer install
fin drush site:install minimal --verbose -y --site-name="FWS: Manatee Rescue and Rehabilitation Database" --account-name=admin --account-pass=admin --config-dir=../config/sync/manatee
fin drush scr ../scripts/manatee/install-cleanup.php
fin drush recipe ../recipes/fws-manatee-content

fin drush cr

# Import taxonomy and nodes.
../scripts/manatee/import-taxonomy.sh && ../scripts/manatee/import-nodes.sh

# fin drush webform-libraries-download

fin drush uli
