#!/bin/bash

## Description: Install the Aerial multisite
## Usage: install-aerial
## Example: "fin install-aerial"

fin composer install

# Run the site installation
# Note: Docksal handles the site URI automatically, so -l is omitted compared to DDEV.
fin drush site:install minimal --yes \
  --account-name=admin \
  --account-pass=admin \
  --verbose \
  --site-name="FWS: Aerial Observer Training and Testing Resources" \
  --config-dir=../config/sync/aerial

# Run install cleanup script
fin drush scr ../scripts/aerial/install-cleanup.php

# Install aerial content recipe
fin drush recipe ../recipes/fws-aerial-content

# Import data
fin drush scr ../scripts/aerial/import-users.php
fin drush scr ../scripts/aerial/import-terms.php
fin drush scr ../scripts/aerial/import-species-photos.php
fin drush scr ../scripts/aerial/import-species-videos.php
# Import sample test data.
fin drush scr ../scripts/aerial/import_test_data.php 100
fin drush cr

fin drush uli
