#!/bin/bash

## Description: Installs FWS.

fin composer install
fin drush site:install minimal --verbose -y --site-name="U.S. Fish & Wildlife Service" --account-name=admin --account-pass=admin
fin drush cr
fin drush recipe ../recipes/fws-core
# fin drush webform-libraries-download
fin drush cr

fin drush scr ../scripts/install-cleanup.php

fin drush recipe ../recipes/fws-manatee
fin drush uli
