#!/bin/bash

## Description: Installs FWS Manatee.

fin composer install
fin drush site:install minimal --verbose -y --site-name="FWS: Manatee Rescue and Rehabilitation Database" --account-name=admin --account-pass=admin
fin drush recipe ../recipes/fws-core
fin drush scr ../scripts/manatee/install-cleanup.php
fin drush cr
fin drush cr
fin drush recipe ../recipes/fws-tracking-taxonomy
fin drush recipe ../recipes/fws-tracking-node
fin drush recipe ../recipes/fws-tracking-reports
fin drush recipe ../recipes/fws-tracking-blocks
fin drush recipe ../recipes/fws-tracking-user
fin drush recipe ../recipes/fws-manatee-content

# fin drush webform-libraries-download

fin drush uli
