#!/usr/bin/env bash

## Description: Installs FWS.

fin composer install
fin drush site:install minimal --verbose -y --site-name="U.S. Fish & Wildlife Service"
fin drush recipe ../recipes/fws-core
# fin drush webform-libraries-download
fin drush cr

fin drush scr ../scripts/install-cleanup.php
