<?php

/**
 * @file
 * Primary module hooks for FWS ID Test module.
 */

/**
 * Implements hook_theme().
 */
function fws_id_test_theme() {
  return [
    'id_test_page' => [
      'variables' => [
        'form' => NULL,
        'module_path' => NULL,
      ],
      'template' => 'id-test-page',
    ],
    'id_test_quiz' => [
      'variables' => [
        'videos' => NULL,
      ],
      'template' => 'id-test-quiz',
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function fws_id_test_preprocess_html(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  // Add 'fws-quiz' class to body for all pages from this module.
  if (strpos($route_name, 'fws_id_test') === 0) {
    $variables['attributes']['class'][] = 'fws-quiz fws-quiz--identification';
  }
}
