name: 'FWS Aerial Content'
description: 'FWS aerial observer sample content.'
type: 'Site'
config:
  actions:
    # Set home page
    system.site:
      simple_config_update:
        page.front: /node/6
        page.403: /node/10
        page.404: /node/8
    # Set main navigation block visibility
    block.block.fws_raf_mainnavigation:
      simple_config_update:
        visibility: { }
    block.block.fws_raf_mainnavigation_2:
      simple_config_update:
        visibility: { }
